-- =====================================================================
-- V18__tax_rate.sql
--
-- 税率（標準・軽減）を店舗ごとに変更できるようにする（FR-B03）。区分自体
-- （STANDARD_10／REDUCED_8）は既存のコードのまま変更せず（呼び方は「標準税率」
-- 「軽減税率」）、実際のパーセンテージだけを店舗設定から編集できるようにする
-- （ロール OWNER の表示名を「経営管理者」に変えた時と同じ考え方。コード自体は変えない）。
--
-- 税率変更には「いつから適用するか」（effective_from）だけを持たせ、終了日は別に
-- 持たない。ある区分の「今有効な税率」は、その区分の中で effective_from が今日以前の
-- 行のうち最も新しいもの（＝次の税率が始まる前日までが暗黙の終了日になる）。
-- 行が1件も無い区分は、フェーズ1導入時点の既定値（STANDARD_10=10%／REDUCED_8=8%）を
-- アプリ層でそのまま使う（このテーブルへの初期データ投入はしない）。
-- =====================================================================

CREATE TABLE tax_rate (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id       BIGINT       NOT NULL REFERENCES store(id),
    tax_category   VARCHAR(20)  NOT NULL CHECK (tax_category IN ('STANDARD_10', 'REDUCED_8')),
    rate_percent   NUMERIC(5,2) NOT NULL,
    effective_from DATE         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_tax_rate_store_category_from UNIQUE (store_id, tax_category, effective_from)
);
-- store_id は uk_tax_rate_store_category_from の先頭列でカバーされる
