-- =====================================================================
-- V1__init_schema.sql
--
-- フェーズ1 初期スキーマ。docs/04_architecture.md 「4. 物理スキーマ（DDL）」を
-- そのまま SQL 化したもの。docs/14 次のステップ 2 の V1__init_schema.sql に相当する。
--
-- 命名・型の規約（04 §4.1）:
--   - 主キー   : id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--                （JPA GenerationType.IDENTITY 互換）
--   - 外部キー : <entity>_id BIGINT REFERENCES <table>(id)
--                FK 制約を持たない非正規化コピー列（company_code）は _id を付けない
--   - 金額     : INTEGER（円・小数なし）、単位サフィックス _jpy
--   - 時刻     : TIMESTAMPTZ（列名 _at） / 日付: DATE / 時刻のみ: TIME
--   - enum     : VARCHAR + CHECK (col IN (...))（DB ネイティブ ENUM 型は使わない）
--   - 論理削除 : マスタ系テーブルは is_active BOOLEAN NOT NULL DEFAULT true
--
-- 監査列の付与（04 §4.1 / §4.2 を突き合わせた本ファイルでの解釈）:
--   - 業務テーブル               : created_at, created_by, updated_at, updated_by
--   - 派生・キュー・リンクテーブル : created_at, updated_at のみ
--       table_session_table / sales_daily_report / sales_report_by_* /
--       reservation_notification / outbound_message
--   - 追記専用イベントテーブル    : 監査列なし（occurred_at / actor を自前で持つ）
--       audit_log / domain_event
--
-- FK 列インデックス（04 §5）:
--   すべての FK 列に B-tree インデックスを張る。ただし UNIQUE 制約または
--   複合インデックスの先頭列で既にカバーされる場合は重複を張らない。
--
-- users テーブルについて:
--   04 §4.3 は「既存 users への ALTER」として書かれているが、これはユーザー実データを
--   バックフィルする検証環境向けの手順。フリーな初期スキーマ（本ファイル）では
--   最終形の CREATE TABLE として一括定義する（到達するスキーマは同一）。
--   既存の開発 DB に ddl-auto=update で作られた古い users がある場合は、
--   `flyway migrate` の前に DROP TABLE users CASCADE すること（README/手順参照）。
-- =====================================================================


-- =====================================================================
-- 4.3 テナント・組織・ユーザー
-- =====================================================================

CREATE TABLE company (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- company_code は URL サブドメインのラベルとして使う（04 §3.1 / §6.1）。
    -- DNS ラベル上限に合わせて VARCHAR(63)。形式・長さは CHECK で強制し、
    -- 予約語（www / api / accounts 等）の拒否はアプリ層で行う。
    company_code     VARCHAR(63)  NOT NULL UNIQUE,
    name             VARCHAR(255) NOT NULL,
    contract_status  VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE'
        CHECK (contract_status IN ('ACTIVE','SUSPENDED','CANCELLED')),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT ck_company_code_format CHECK (
        company_code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
        AND char_length(company_code) BETWEEN 3 AND 63
    )
);

CREATE TABLE store (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT       NOT NULL REFERENCES company(id),
    name           VARCHAR(255) NOT NULL,
    address        VARCHAR(500),
    phone          VARCHAR(30),
    business_hours VARCHAR(255),
    seat_count     INTEGER      NOT NULL DEFAULT 0,
    timezone       VARCHAR(50)  NOT NULL DEFAULT 'Asia/Tokyo',
    is_active      BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
-- store は company から1ホップのため company_code の非正規化コピーは持たない（§3.1）
CREATE INDEX ix_store_company_id ON store (company_id);

CREATE TABLE store_setting (
    store_id             BIGINT PRIMARY KEY REFERENCES store(id),
    tax_rounding         VARCHAR(20) NOT NULL DEFAULT 'FLOOR'
        CHECK (tax_rounding IN ('FLOOR','CEIL','ROUND')),
    price_includes_tax   BOOLEAN NOT NULL DEFAULT true,
    invoice_reg_no       VARCHAR(20),
    web_reservation_mode VARCHAR(20) NOT NULL DEFAULT 'APPROVAL'
        CHECK (web_reservation_mode IN ('APPROVAL','INSTANT')),
    mobile_order_enabled          BOOLEAN NOT NULL DEFAULT false,
    last_order_default_min        INTEGER NOT NULL DEFAULT 30,
    cancel_charge_default_customer BOOLEAN NOT NULL DEFAULT true,
    cancel_charge_default_store    BOOLEAN NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);

-- 04 §4.3 の「既存 users への ALTER」を、初期スキーマでは最終形として一括定義する。
CREATE TABLE users (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT       NOT NULL REFERENCES company(id),
    store_id           BIGINT       REFERENCES store(id),
    name               VARCHAR(255) NOT NULL,
    email              VARCHAR(255) NOT NULL,
    password           VARCHAR(255) NOT NULL,
    telnumber          VARCHAR(255),
    role               VARCHAR(20)  NOT NULL DEFAULT 'OWNER'
        CHECK (role IN ('OWNER','MANAGER','HALL','KITCHEN','PARTTIME')),
    status             VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE','LOCKED','INVITED')),
    two_factor_enabled BOOLEAN      NOT NULL DEFAULT false,
    -- ログイン失敗の連続回数による一時ロック（FR-A08）。上限到達で status='LOCKED' ＋
    -- locked_until を設定し、locked_until 経過後の次回アクセスでアプリ層が自動解除する。
    failed_login_count INTEGER      NOT NULL DEFAULT 0,
    locked_until        TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_users_company_id_email UNIQUE (company_id, email)
);
-- company_id は uk_users_company_id_email の先頭列でカバーされるため単独 index は張らない
CREATE INDEX ix_users_store_id ON users (store_id);

CREATE TABLE user_invitation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT       NOT NULL REFERENCES company(id),
    store_id    BIGINT       REFERENCES store(id),
    email       VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL
        CHECK (role IN ('OWNER','MANAGER','HALL','KITCHEN','PARTTIME')),
    token       VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    accepted_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_user_invitation_token      ON user_invitation (token);
CREATE INDEX ix_user_invitation_company_id ON user_invitation (company_id);
CREATE INDEX ix_user_invitation_store_id   ON user_invitation (store_id);


-- =====================================================================
-- 4.4 マスタ（メニュー・卓・コース・決済手段）
-- =====================================================================

CREATE TABLE menu_category (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code  VARCHAR(63)  NOT NULL,               -- 非正規化コピー（FK 制約なし。§3.1）
    store_id      BIGINT       NOT NULL REFERENCES store(id),
    name          VARCHAR(100) NOT NULL,
    display_order INTEGER      NOT NULL DEFAULT 0,
    is_active     BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_menu_category_store_id ON menu_category (store_id);

CREATE TABLE menu_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code    VARCHAR(63)  NOT NULL,             -- 非正規化コピー（FK 制約なし。§3.1）
    store_id        BIGINT       NOT NULL REFERENCES store(id),
    category_id     BIGINT       NOT NULL REFERENCES menu_category(id),
    prep_type       VARCHAR(20)  NOT NULL DEFAULT 'COOK'
        CHECK (prep_type IN ('COOK','NO_COOK')),       -- NO_COOK は調理 KDS / kitchen_ticket 対象外（§9）
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    price_jpy       INTEGER      NOT NULL,
    tax_category    VARCHAR(20)  NOT NULL
        CHECK (tax_category IN ('STANDARD_10','REDUCED_8')),
    photo_url       VARCHAR(500),
    serve_time_from TIME,
    serve_time_to   TIME,
    available_from  TIMESTAMPTZ,
    available_to    TIMESTAMPTZ,
    sales_status    VARCHAR(20)  NOT NULL DEFAULT 'ON_SALE'
        CHECK (sales_status IN ('ON_SALE','SOLD_OUT','SUSPENDED')),
    display_order   INTEGER      NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_menu_item_store_category ON menu_item (store_id, category_id);
CREATE INDEX ix_menu_item_category_id    ON menu_item (category_id);

CREATE TABLE menu_option_group (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id     BIGINT       NOT NULL REFERENCES store(id),
    menu_item_id BIGINT       REFERENCES menu_item(id),  -- フェーズ1は実質必須（商品固有オプションのみ）
    name         VARCHAR(100) NOT NULL,
    min_select   INTEGER      NOT NULL DEFAULT 0,
    max_select   INTEGER      NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_menu_option_group_store_id     ON menu_option_group (store_id);
CREATE INDEX ix_menu_option_group_menu_item_id ON menu_option_group (menu_item_id);

CREATE TABLE menu_option (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_group_id BIGINT       NOT NULL REFERENCES menu_option_group(id),
    name            VARCHAR(100) NOT NULL,
    price_delta_jpy INTEGER      NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_menu_option_option_group_id ON menu_option (option_group_id);

CREATE TABLE course (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id              BIGINT       NOT NULL REFERENCES store(id),
    name                  VARCHAR(255) NOT NULL,
    type                  VARCHAR(20)  NOT NULL
        CHECK (type IN ('COURSE','FREE_DRINK')),
    duration_min          INTEGER      NOT NULL,
    last_order_before_min INTEGER      NOT NULL DEFAULT 30,
    price_jpy             INTEGER      NOT NULL,
    is_active             BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_course_store_id ON course (store_id);

CREATE TABLE dining_table (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id   BIGINT      NOT NULL REFERENCES store(id),
    table_no   VARCHAR(20) NOT NULL,
    seat_count INTEGER     NOT NULL,
    area       VARCHAR(100),
    qr_token   VARCHAR(64) NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'EMPTY'
        CHECK (status IN ('EMPTY','OCCUPIED','BILLING')),
    is_active  BOOLEAN     NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_dining_table_store_table_no UNIQUE (store_id, table_no),
    CONSTRAINT uk_dining_table_store_qr_token UNIQUE (store_id, qr_token)
);
-- store_id は uk_dining_table_store_table_no の先頭列でカバーされる

CREATE TABLE payment_method_config (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id       BIGINT      NOT NULL REFERENCES store(id),
    method_type    VARCHAR(20) NOT NULL
        CHECK (method_type IN ('CASH','PAYPAY','CREDIT_CARD','RAKUTEN_PAY')),
    enabled        BOOLEAN     NOT NULL DEFAULT false,
    display_name   VARCHAR(100),
    credential_enc BYTEA,
    note           VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_payment_method_config_store_method UNIQUE (store_id, method_type)
);
-- store_id は uk_payment_method_config_store_method の先頭列でカバーされる

CREATE TABLE store_business_day (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id             BIGINT   NOT NULL REFERENCES store(id),
    business_date        DATE,
    weekday              SMALLINT CHECK (weekday BETWEEN 0 AND 6),
    is_open              BOOLEAN  NOT NULL DEFAULT true,
    open_time            TIME,
    close_time           TIME,
    reservation_capacity INTEGER,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    -- business_date（特定日）と weekday（曜日既定）はどちらか一方のみ
    CONSTRAINT ck_store_business_day_date_xor_weekday
        CHECK ((business_date IS NOT NULL) <> (weekday IS NOT NULL))
);
CREATE INDEX ix_store_business_day_store_id ON store_business_day (store_id);


-- =====================================================================
-- 4.5 予約
-- =====================================================================

CREATE TABLE reservation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code     VARCHAR(63)  NOT NULL,            -- 非正規化コピー（FK 制約なし。§3.1）
    store_id         BIGINT       NOT NULL REFERENCES store(id),
    reserved_at      TIMESTAMPTZ  NOT NULL,
    party_size       INTEGER      NOT NULL,
    guest_name       VARCHAR(100) NOT NULL,
    guest_phone      VARCHAR(30),
    guest_email      VARCHAR(255),
    request_note     TEXT,
    course_id        BIGINT       REFERENCES course(id),
    channel          VARCHAR(20)  NOT NULL
        CHECK (channel IN ('WEB','PHONE','WALK_IN')),
    status           VARCHAR(20)  NOT NULL DEFAULT 'REQUESTED'
        CHECK (status IN ('REQUESTED','CONFIRMED','SEATED','DONE','CANCELLED','NO_SHOW')),
    confirmed_by     VARCHAR(255),
    confirmed_at     TIMESTAMPTZ,
    cancelled_reason VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_reservation_store_date ON reservation (store_id, reserved_at);
CREATE INDEX ix_reservation_course_id  ON reservation (course_id);

CREATE TABLE reservation_notification (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT       NOT NULL REFERENCES reservation(id),
    type           VARCHAR(20)  NOT NULL CHECK (type IN ('CONFIRM','REMINDER')),
    channel        VARCHAR(20)  NOT NULL CHECK (channel IN ('EMAIL','SMS')),
    "to"           VARCHAR(255) NOT NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'QUEUED'
        CHECK (status IN ('QUEUED','SENT','FAILED')),
    sent_at        TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ
);
CREATE INDEX ix_reservation_notification_reservation_id ON reservation_notification (reservation_id);


-- =====================================================================
-- 4.6 来店・卓セッション・注文
-- =====================================================================

CREATE TABLE table_session (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code      VARCHAR(63)  NOT NULL,           -- 非正規化コピー（FK 制約なし。§3.1）
    store_id          BIGINT       NOT NULL REFERENCES store(id),
    status            VARCHAR(20)  NOT NULL DEFAULT 'OPEN'
        CHECK (status IN ('OPEN','BILLING','CLOSED')),
    opened_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    opened_by         VARCHAR(255) NOT NULL,
    closed_at         TIMESTAMPTZ,
    party_size        INTEGER      NOT NULL,
    reservation_id    BIGINT       REFERENCES reservation(id),
    course_id         BIGINT       REFERENCES course(id),
    course_started_at TIMESTAMPTZ,
    last_order_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_table_session_store_status  ON table_session (store_id, status);
CREATE INDEX ix_table_session_reservation_id ON table_session (reservation_id);
CREATE INDEX ix_table_session_course_id      ON table_session (course_id);

CREATE TABLE table_session_table (
    table_session_id BIGINT  NOT NULL REFERENCES table_session(id),
    dining_table_id  BIGINT  NOT NULL REFERENCES dining_table(id),
    is_primary       BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    PRIMARY KEY (table_session_id, dining_table_id)
);
-- table_session_id は複合 PK の先頭列でカバーされる
CREATE INDEX ix_table_session_table_dining_table_id ON table_session_table (dining_table_id);

CREATE TABLE mobile_order_session (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_session_id BIGINT      NOT NULL REFERENCES table_session(id),
    qr_token         VARCHAR(64) NOT NULL UNIQUE,
    issued_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at       TIMESTAMPTZ NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE','EXPIRED')),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_mobile_order_session_table_session_id ON mobile_order_session (table_session_id);

CREATE TABLE staff_device (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code      VARCHAR(63) NOT NULL,            -- 非正規化コピー（FK 制約なし。§3.1）
    store_id          BIGINT      NOT NULL REFERENCES store(id),
    device_code       VARCHAR(20) NOT NULL,            -- 端末ID。例 'S12-07'
    label             VARCHAR(100),
    status            VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE','RETIRED')),
    last_accepted_seq BIGINT      NOT NULL DEFAULT 0,  -- 受理済み最大連番。これ以下は再送
    retired_at        TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_staff_device_store_device_code UNIQUE (store_id, device_code)
);
-- store_id は uk_staff_device_store_device_code の先頭列でカバーされる

CREATE TABLE customer_order (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_session_id        BIGINT      NOT NULL REFERENCES table_session(id),
    source                  VARCHAR(20) NOT NULL CHECK (source IN ('STAFF','MOBILE')),
    entered_by              VARCHAR(255),
    mobile_order_session_id BIGINT      REFERENCES mobile_order_session(id),
    client_ref_id           VARCHAR(40),                -- 端末ID + '-' + 端末内グローバル連番（§9）
    status                  VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED'
        CHECK (status IN ('SUBMITTED','ACCEPTED','REJECTED')),
    submitted_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    accepted_by             VARCHAR(255),
    accepted_at             TIMESTAMPTZ,
    reject_reason           VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_customer_order_session_client_ref UNIQUE (table_session_id, client_ref_id)
);
-- table_session_id は uk_customer_order_session_client_ref の先頭列でカバーされる
CREATE INDEX ix_customer_order_mobile_order_session_id ON customer_order (mobile_order_session_id);

CREATE TABLE order_line (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                 BIGINT       NOT NULL REFERENCES customer_order(id),
    table_session_id         BIGINT       NOT NULL REFERENCES table_session(id),
    menu_item_id             BIGINT       NOT NULL REFERENCES menu_item(id),
    item_name_snap           VARCHAR(255) NOT NULL,
    unit_price_snap_jpy      INTEGER      NOT NULL,
    tax_category_snap        VARCHAR(20)  NOT NULL,
    quantity                 INTEGER      NOT NULL,
    note                     VARCHAR(500),
    serve_status             VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
        CHECK (serve_status IN ('PENDING','PREPARING','SERVED','CANCELLED','REJECTED')),
    fire_state               VARCHAR(20)  NOT NULL DEFAULT 'FIRED'
        CHECK (fire_state IN ('HELD','FIRED')),          -- HELD=後出し保留（調理 KDS 非表示）。§9
    fired_at                 TIMESTAMPTZ,                -- HELD→FIRED の時刻。§9
    fired_by                 VARCHAR(255),
    registered_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),  -- オフライン分はスキュー補正後（§9）
    registered_by            VARCHAR(255) NOT NULL,
    registered_at_device_raw TIMESTAMPTZ,                -- オフライン分のみ。補正前の端末時計値（§9）
    business_date            DATE         NOT NULL,      -- 注文営業日（§9）
    time_low_confidence      BOOLEAN      NOT NULL DEFAULT false,  -- スキュー補正が信用できない（§9）
    served_at                TIMESTAMPTZ,
    cancelled_at             TIMESTAMPTZ,
    cancelled_by             VARCHAR(255),
    cancel_reason            VARCHAR(20)
        CHECK (cancel_reason IN ('ORDER_MISTAKE','QUALITY','DELAY','WRONG_SERVE','SOLD_OUT','CUSTOMER','OTHER')),
    cancel_chargeable        BOOLEAN,
    was_cooked               BOOLEAN,
    remake_of_line_id        BIGINT       REFERENCES order_line(id),
    client_ref_id            VARCHAR(40),                -- オフライン作成分のみ（§9）
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_order_line_session_client_ref UNIQUE (table_session_id, client_ref_id)
);
CREATE INDEX ix_order_line_table_session   ON order_line (table_session_id);
CREATE INDEX ix_order_line_business_date   ON order_line (business_date);
CREATE INDEX ix_order_line_order_id        ON order_line (order_id);
CREATE INDEX ix_order_line_menu_item_id    ON order_line (menu_item_id);
CREATE INDEX ix_order_line_remake_of_line_id ON order_line (remake_of_line_id);

CREATE TABLE order_line_option (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_line_id        BIGINT       NOT NULL REFERENCES order_line(id),
    option_name_snap     VARCHAR(100) NOT NULL,
    price_delta_snap_jpy INTEGER      NOT NULL DEFAULT 0,
    client_ref_id        VARCHAR(40),                    -- オフライン作成分のみ（§9）
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_order_line_option_line_client_ref UNIQUE (order_line_id, client_ref_id)
);
-- order_line_id は uk_order_line_option_line_client_ref の先頭列でカバーされる

CREATE TABLE kitchen_ticket (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT      NOT NULL REFERENCES customer_order(id),
    store_id        BIGINT      NOT NULL REFERENCES store(id),
    status          VARCHAR(20) NOT NULL DEFAULT 'NEW'
        CHECK (status IN ('NEW','IN_PROGRESS','DONE')),
    offline_settled BOOLEAN     NOT NULL DEFAULT false,  -- 同期時に status=DONE で起こした伝票のみ true（§9）
    printed_at      TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_kitchen_ticket_order_id ON kitchen_ticket (order_id);
CREATE INDEX ix_kitchen_ticket_store_id ON kitchen_ticket (store_id);


-- =====================================================================
-- 4.7 会計・決済
-- =====================================================================

CREATE TABLE guest_check (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_session_id   BIGINT      NOT NULL REFERENCES table_session(id),
    store_id           BIGINT      NOT NULL REFERENCES store(id),
    seq_in_session     INTEGER     NOT NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'OPEN'
        CHECK (status IN ('OPEN','FINALIZED','VOIDED')),
    subtotal_jpy       INTEGER     NOT NULL DEFAULT 0,
    discount_total_jpy INTEGER     NOT NULL DEFAULT 0,
    tax_total_jpy      INTEGER     NOT NULL DEFAULT 0,
    total_jpy          INTEGER     NOT NULL DEFAULT 0,
    split_type         VARCHAR(20) NOT NULL DEFAULT 'NONE'
        CHECK (split_type IN ('NONE','BY_HEAD','BY_ITEM')),
    split_count        INTEGER,
    business_date      DATE        NOT NULL,
    finalized_at       TIMESTAMPTZ,
    finalized_by       VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_guest_check_session_seq UNIQUE (table_session_id, seq_in_session)
);
-- table_session_id は uk_guest_check_session_seq の先頭列でカバーされる
CREATE INDEX ix_guest_check_store_business_date ON guest_check (store_id, business_date);

CREATE TABLE guest_check_line (
    id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id      BIGINT  NOT NULL REFERENCES guest_check(id),
    order_line_id BIGINT  NOT NULL REFERENCES order_line(id),
    amount_jpy    INTEGER NOT NULL,
    quantity      INTEGER NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_guest_check_line_order_line UNIQUE (order_line_id)  -- 1 order_line は1会計のみ（§5 不変条件12）
);
CREATE INDEX ix_guest_check_line_check_id ON guest_check_line (check_id);

CREATE TABLE guest_check_discount (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id   BIGINT        NOT NULL REFERENCES guest_check(id),
    type       VARCHAR(20)   NOT NULL CHECK (type IN ('AMOUNT','RATE','COUPON','ROUNDING')),
    value      NUMERIC(10,2) NOT NULL,
    amount_jpy INTEGER       NOT NULL,
    reason     VARCHAR(255),
    applied_by VARCHAR(255)  NOT NULL,
    applied_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_guest_check_discount_check_id ON guest_check_discount (check_id);

CREATE TABLE guest_check_tax_line (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id           BIGINT      NOT NULL REFERENCES guest_check(id),
    tax_category       VARCHAR(20) NOT NULL
        CHECK (tax_category IN ('STANDARD_10','REDUCED_8')),
    taxable_amount_jpy INTEGER     NOT NULL,
    tax_amount_jpy     INTEGER     NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_guest_check_tax_line_check_category UNIQUE (check_id, tax_category)
);
-- check_id は uk_guest_check_tax_line_check_category の先頭列でカバーされる

CREATE TABLE payment (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id       BIGINT      NOT NULL REFERENCES guest_check(id),
    method_type    VARCHAR(20) NOT NULL
        CHECK (method_type IN ('CASH','PAYPAY','CREDIT_CARD','RAKUTEN_PAY')),
    amount_jpy     INTEGER     NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('SUCCESS','FAILED','PENDING')),
    external_txn_id VARCHAR(100),
    tendered_jpy   INTEGER,
    change_jpy     INTEGER,
    is_manual_entry BOOLEAN    NOT NULL DEFAULT false,
    processed_at   TIMESTAMPTZ,
    processed_by   VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_payment_check_id ON payment (check_id);
-- Webhook 再送の冪等性（§7.3）
CREATE UNIQUE INDEX ux_payment_external_txn ON payment (method_type, external_txn_id)
    WHERE external_txn_id IS NOT NULL;

CREATE TABLE refund (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id    BIGINT       NOT NULL REFERENCES guest_check(id),
    payment_id  BIGINT       REFERENCES payment(id),
    amount_jpy  INTEGER      NOT NULL,
    reason      VARCHAR(255) NOT NULL,
    reason_note VARCHAR(500),
    executed_by VARCHAR(255) NOT NULL,
    executed_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    approved_by VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_refund_check_id   ON refund (check_id);
CREATE INDEX ix_refund_payment_id ON refund (payment_id);

CREATE TABLE receipt (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id            BIGINT       NOT NULL REFERENCES guest_check(id),
    type                VARCHAR(20)  NOT NULL CHECK (type IN ('RECEIPT','INVOICE')),
    addressee           VARCHAR(255),
    proviso             VARCHAR(255),
    issued_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    pdf_ref             VARCHAR(500) NOT NULL,
    invoice_reg_no_snap VARCHAR(20),
    tax_lines_snap      JSONB        NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_receipt_check_id ON receipt (check_id);


-- =====================================================================
-- 4.8 日次締め・売上日報
-- =====================================================================

CREATE TABLE daily_close (
    id                   BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id             BIGINT      NOT NULL REFERENCES store(id),
    business_date        DATE        NOT NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'OPEN'
        CHECK (status IN ('OPEN','CLOSED')),
    closed_by            VARCHAR(255),
    closed_at            TIMESTAMPTZ,
    cash_counted_jpy     INTEGER,
    cash_theoretical_jpy INTEGER,
    cash_diff_jpy        INTEGER,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255),
    CONSTRAINT uk_daily_close_store_business_date UNIQUE (store_id, business_date)
);
-- store_id は uk_daily_close_store_business_date の先頭列でカバーされる

CREATE TABLE sales_daily_report (
    id                 BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_close_id     BIGINT  NOT NULL REFERENCES daily_close(id),
    store_id           BIGINT  NOT NULL REFERENCES store(id),
    business_date      DATE    NOT NULL,
    sales_total_jpy    INTEGER NOT NULL,
    guest_count        INTEGER NOT NULL,
    group_count        INTEGER NOT NULL,
    avg_per_guest_jpy  INTEGER NOT NULL,
    discount_total_jpy INTEGER NOT NULL,
    refund_total_jpy   INTEGER NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ
);
CREATE INDEX ix_sales_daily_report_daily_close_id ON sales_daily_report (daily_close_id);
CREATE INDEX ix_sales_daily_report_store_id       ON sales_daily_report (store_id);

CREATE TABLE sales_report_by_payment (
    id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_daily_report_id BIGINT      NOT NULL REFERENCES sales_daily_report(id),
    method_type           VARCHAR(20) NOT NULL,
    amount_jpy            INTEGER      NOT NULL,
    txn_count             INTEGER      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ
);
CREATE INDEX ix_sales_report_by_payment_report_id ON sales_report_by_payment (sales_daily_report_id);

CREATE TABLE sales_report_by_tax (
    id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_daily_report_id BIGINT      NOT NULL REFERENCES sales_daily_report(id),
    tax_category          VARCHAR(20) NOT NULL,
    sales_amount_jpy      INTEGER     NOT NULL,
    tax_amount_jpy        INTEGER     NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ
);
CREATE INDEX ix_sales_report_by_tax_report_id ON sales_report_by_tax (sales_daily_report_id);

CREATE TABLE sales_report_by_hour (
    id                    BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_daily_report_id BIGINT   NOT NULL REFERENCES sales_daily_report(id),
    hour                  SMALLINT NOT NULL CHECK (hour BETWEEN 0 AND 23),
    sales_amount_jpy      INTEGER  NOT NULL,
    guest_count           INTEGER  NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ
);
CREATE INDEX ix_sales_report_by_hour_report_id ON sales_report_by_hour (sales_daily_report_id);


-- =====================================================================
-- 4.9 スタッフ・シフト・勤怠
-- =====================================================================

CREATE TABLE staff (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id        BIGINT       NOT NULL REFERENCES store(id),
    user_id         BIGINT       REFERENCES users(id),   -- 非ログインスタッフは NULL（§4.9）
    name            VARCHAR(100) NOT NULL,
    role            VARCHAR(50),                          -- 表示ラベル（認可は users.role）
    hourly_wage_jpy INTEGER,
    contact         VARCHAR(255),
    is_active       BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_staff_store_id ON staff (store_id);
CREATE INDEX ix_staff_user_id  ON staff (user_id);

CREATE TABLE staff_availability (
    id         BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id   BIGINT   NOT NULL REFERENCES staff(id),
    weekday    SMALLINT NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    start_time TIME     NOT NULL,
    end_time   TIME     NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_staff_availability_staff_id ON staff_availability (staff_id);

CREATE TABLE shift_request (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id     BIGINT      NOT NULL REFERENCES staff(id),
    target_date  DATE        NOT NULL,
    type         VARCHAR(20) NOT NULL CHECK (type IN ('AVAILABLE','UNAVAILABLE')),
    start_time   TIME,
    end_time     TIME,
    comment      VARCHAR(500),
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_shift_request_staff_id ON shift_request (staff_id);

CREATE TABLE shift_schedule (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id     BIGINT      NOT NULL REFERENCES store(id),
    period_start DATE        NOT NULL,
    period_end   DATE        NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT','PUBLISHED')),
    published_at TIMESTAMPTZ,
    created_by   VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_shift_schedule_store_id ON shift_schedule (store_id);

CREATE TABLE shift_assignment (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_schedule_id BIGINT     NOT NULL REFERENCES shift_schedule(id),
    staff_id         BIGINT      NOT NULL REFERENCES staff(id),
    work_date        DATE        NOT NULL,
    start_time       TIME        NOT NULL,
    end_time         TIME        NOT NULL,
    position         VARCHAR(50),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_shift_assignment_shift_schedule_id ON shift_assignment (shift_schedule_id);
CREATE INDEX ix_shift_assignment_staff_id          ON shift_assignment (staff_id);

CREATE TABLE time_clock (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id        BIGINT      NOT NULL REFERENCES staff(id),
    store_id        BIGINT      NOT NULL REFERENCES store(id),
    work_date       DATE        NOT NULL,
    clock_in_at     TIMESTAMPTZ,
    clock_out_at    TIMESTAMPTZ,
    is_corrected    BOOLEAN     NOT NULL DEFAULT false,
    corrected_by    VARCHAR(255),
    correction_note VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);
CREATE INDEX ix_time_clock_staff_id ON time_clock (staff_id);
CREATE INDEX ix_time_clock_store_id ON time_clock (store_id);


-- =====================================================================
-- 4.10 監査・イベント・通知（基盤）
--
-- audit_log / domain_event は occurred_at の月次レンジパーティション（§8）。
-- 本番では pg_partman で自動管理する。V1 では最低限の稼働のため DEFAULT
-- パーティションを1つ用意しておき、pg_partman 導入時に定期パーティションへ移す。
-- パーティションテーブルの PK にはパーティションキー（occurred_at）を含める必要がある。
-- =====================================================================

CREATE TABLE audit_log (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    company_code   VARCHAR(63)  NOT NULL,               -- 非正規化コピー（FK 制約なし。§3.1）
    store_id       BIGINT       REFERENCES store(id),
    actor          VARCHAR(255) NOT NULL,
    action         VARCHAR(50)  NOT NULL,
    target_type    VARCHAR(50)  NOT NULL,
    target_id      BIGINT,
    before_summary TEXT,
    after_summary  TEXT,
    ip             VARCHAR(45),
    device         VARCHAR(255),
    occurred_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE TABLE audit_log_default PARTITION OF audit_log DEFAULT;
CREATE INDEX ix_audit_log_company_occurred ON audit_log (company_code, occurred_at);
CREATE INDEX ix_audit_log_store_id         ON audit_log (store_id);

CREATE TABLE domain_event (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    company_code   VARCHAR(63)  NOT NULL,               -- 非正規化コピー（FK 制約なし。§3.1）
    store_id       BIGINT       REFERENCES store(id),
    aggregate_type VARCHAR(30)  NOT NULL
        CHECK (aggregate_type IN ('TABLE_SESSION','ORDER_LINE','CHECK','PAYMENT','DAILY_CLOSE')),
    aggregate_id   BIGINT       NOT NULL,
    event_type     VARCHAR(50)  NOT NULL,
    payload        JSONB        NOT NULL,
    occurred_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actor          VARCHAR(255) NOT NULL,
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE TABLE domain_event_default PARTITION OF domain_event DEFAULT;
CREATE INDEX ix_domain_event_aggregate        ON domain_event (aggregate_type, aggregate_id);
CREATE INDEX ix_domain_event_company_occurred ON domain_event (company_code, occurred_at);
CREATE INDEX ix_domain_event_store_id         ON domain_event (store_id);

CREATE TABLE outbound_message (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT       NOT NULL REFERENCES store(id),
    type     VARCHAR(20)  NOT NULL CHECK (type IN ('EMAIL','SMS')),
    "to"     VARCHAR(255) NOT NULL,
    template VARCHAR(100) NOT NULL,
    status   VARCHAR(20)  NOT NULL DEFAULT 'QUEUED'
        CHECK (status IN ('QUEUED','SENT','FAILED')),
    sent_at  TIMESTAMPTZ,
    error    VARCHAR(500),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ
);
CREATE INDEX ix_outbound_message_store_id ON outbound_message (store_id);
