-- =====================================================================
-- V2__app_features.sql
--
-- ログイン後の共通トップ画面（ホーム）に並べる機能の入口を、フロントのコードへ直書きする代わりに
-- DBで管理する。テナント（company/store）に紐づかない、アプリ全体で共通の設定。
-- 命名・型の規約は V1 冒頭コメントに準じる。
--
-- app_feature（既存の menu_item「飲食メニュー」とは無関係。名前の衝突を避けるため
-- app_feature とした）は、ホーム画面のカード1件＝1行。app_feature_role は
-- そのカードをどのロールに表示するかを持つ多対多の中間テーブル。
-- =====================================================================

CREATE TABLE app_feature (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_key    VARCHAR(50)  NOT NULL UNIQUE,   -- 画面遷移先の識別子（例 'store'）
    title          VARCHAR(100) NOT NULL,
    description    VARCHAR(255),
    path           VARCHAR(255) NOT NULL,          -- フロントのルーティングパス（例 '/settings/store'）
    display_order  INTEGER      NOT NULL DEFAULT 0,
    is_active      BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255) NOT NULL,
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(255)
);

CREATE TABLE app_feature_role (
    app_feature_id BIGINT      NOT NULL REFERENCES app_feature(id),
    role           VARCHAR(20) NOT NULL
        CHECK (role IN ('OWNER','MANAGER','HALL','KITCHEN','PARTTIME')),
    PRIMARY KEY (app_feature_id, role)
);
-- app_feature_id は複合PKの先頭列でカバーされる

-- 従来フロント（features.ts）に直書きしていた内容を初期データとして投入する。
INSERT INTO app_feature (feature_key, title, description, path, display_order, created_by) VALUES
    ('store',           '店舗設定',       '店舗の基本情報と税の設定',                     '/settings/store',           1, 'system'),
    ('tables',          '卓（テーブル）', '卓の追加・編集・並び順',                       '/settings/tables',          2, 'system'),
    ('payment-methods', '決済手段',       '現金・PayPay・クレジットカード等の有効／無効', '/settings/payment-methods', 3, 'system'),
    ('business-days',   '営業日',         '曜日ごとの営業設定と臨時休業',                 '/settings/business-days',   4, 'system');

INSERT INTO app_feature_role (app_feature_id, role)
SELECT f.id, r.role
FROM app_feature f, UNNEST(ARRAY['OWNER', 'MANAGER']) AS r(role)
WHERE f.feature_key IN ('store', 'tables', 'payment-methods', 'business-days');
