-- =====================================================================
-- V5__password_reset_token.sql
--
-- パスワードを忘れた場合のリセット（FR-A04・EXT-03）。トークンは平文では保存せず、
-- SHA-256ハッシュ（16進64文字）で保存する（メールに載る値そのものがDB漏えい時に使えないように）。
-- =====================================================================

CREATE TABLE password_reset_token (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users(id),
    token_hash  VARCHAR(64)  NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    used_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ
);
CREATE INDEX ix_password_reset_token_user_id ON password_reset_token (user_id);
